name: myapp
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  riverpod: ^2.5.1
  

dev_dependencies:
  
  lints: ^3.0.0
  test: ^1.24.0
